[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Literate = "98b08198-f543-4a55-a0ac-dd88466e8e06"
SCIP = "82193955-e24f-5292-bf16-6f2c5261a85f"

[compat]
Documenter = "1.8"
Literate = "3"
